import { useState } from 'react'
import ApiResponsePanel from '../components/ApiResponsePanel'
import ResultCard from '../components/ResultCard'
import { runMeetingPipeline } from '../services/api'
import { downloadPdf, shareViaEmail } from '../utils/exportPdf'
import { usePageState } from '../context/PageStateContext'

export default function PipelineRunner({ theme }) {
  const [pageState, setPageState] = usePageState("pipeline-runner");
  const transcript = pageState?.transcript ?? ''
  const useSample = pageState?.useSample ?? true
  const result = pageState?.result ?? null
  const setTranscript = (v) => setPageState((s) => ({ ...s, transcript: v }))
  const setUseSample = (v) => setPageState((s) => ({ ...s, useSample: v }))
  const setResult = (v) => setPageState((s) => ({ ...s, result: v }))
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  const submit = async (event) => {
    event.preventDefault()
    setLoading(true)
    setError('')
    try {
      const response = await runMeetingPipeline(transcript, useSample)
      setResult(response)
    } catch (err) {
      setError(err.message || 'Unable to run the meeting pipeline.')
    } finally {
      setLoading(false)
    }
  }

  const handleDownloadPdf = () => {
    if (!result?.summary_data) return
    downloadPdf({
      title: 'Meeting Pipeline Report',
      subtitle: 'Summarization and Notion Integration Output',
      filename: 'meeting_pipeline_report.pdf',
      sections: [
        {
          title: 'Pipeline Summary',
          subtitle: 'Executive overview generated by backend pipeline',
          content: result.summary_data.summary || 'No summary returned.',
        },
        {
          title: 'Notion Sync Status',
          subtitle: 'Notion integration response',
          content: result.notion?.message || 'No Notion status returned.',
        },
      ],
    })
  }

  const handleShareEmail = () => {
    if (!result?.summary_data) return
    const body = `Hi,\n\nHere are the results from the Meeting Pipeline:\n\n=== PIPELINE SUMMARY ===\n${result.summary_data.summary || 'N/A'}\n\n=== NOTION SYNC ===\n${result.notion?.message || 'N/A'}\n\n---\nSent via AgentX Meeting Pipeline`
    shareViaEmail({
      subject: 'Meeting Pipeline Results & Summary',
      body,
    })
  }

  return (
    <div className="space-y-6">
      <ResultCard
        title="Meeting Pipeline"
        subtitle="Run transcript summarization and Notion sync through the backend pipeline endpoint."
        theme={theme}
      >
        <form className="space-y-4" onSubmit={submit}>
          <label className="flex items-center gap-3 text-sm text-slate-400">
            <input
              type="checkbox"
              checked={useSample}
              onChange={(event) => setUseSample(event.target.checked)}
            />
            Use bundled sample transcript when no custom transcript is provided
          </label>

          <textarea
            value={transcript}
            onChange={(event) => setTranscript(event.target.value)}
            rows={10}
            placeholder="Paste a meeting transcript here to run the full pipeline..."
            className={`w-full rounded-3xl border px-4 py-4 text-sm outline-none transition ${theme === 'dark'
              ? 'border-white/10 bg-slate-950/60 text-slate-100 placeholder:text-slate-500'
              : 'border-[#D3CBB8] bg-[#FAF8F5] text-stone-800 placeholder:text-stone-400 focus:border-clay'
              }`}
          />

          {error ? (
            <div className="rounded-2xl border border-rose-400/30 bg-rose-500/10 px-4 py-3 text-sm text-rose-300">{error}</div>
          ) : null}

          <button
            type="submit"
            disabled={loading}
            className={`rounded-2xl px-5 py-3 text-sm font-semibold transition disabled:cursor-not-allowed disabled:opacity-60 ${theme === 'dark' ? 'bg-amber-400 text-slate-950 hover:bg-amber-300' : 'bg-clay text-white hover:bg-clay/90'
              }`}
          >
            {loading ? 'Running pipeline…' : 'Run Pipeline'}
          </button>
        </form>
      </ResultCard>

      {result?.summary_data ? (
        <ResultCard
          title="Pipeline Summary"
          subtitle="Returned by /pipeline/run"
          theme={theme}
          actions={
            <div className="flex flex-wrap gap-2">
              <button
                type="button"
                onClick={handleShareEmail}
                className={`flex items-center gap-2 rounded-2xl border px-4 py-2 text-sm font-semibold transition ${theme === 'dark'
                  ? 'border-purple-500/30 bg-purple-500/10 text-purple-300 hover:bg-purple-500/20'
                  : 'border-clay/30 bg-clay/10 text-clay hover:bg-clay/20'
                  }`}
              >
                <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 002-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                </svg>
                Share via Email
              </button>
              <button
                type="button"
                onClick={handleDownloadPdf}
                className={`flex items-center gap-2 rounded-2xl border px-4 py-2 text-sm font-semibold transition ${theme === 'dark'
                  ? 'border-amber-500/30 bg-amber-500/10 text-amber-300 hover:bg-amber-500/20'
                  : 'border-clay/30 bg-clay/10 text-clay hover:bg-clay/20'
                  }`}
              >
                <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
                Download PDF
              </button>
            </div>
          }
        >

          <div className="space-y-4 text-sm text-slate-300">
            <div>
              <div className={`text-xs uppercase tracking-[0.2em] ${theme === 'dark' ? 'text-amber-400' : 'text-forest font-semibold'}`}>Summary</div>
              <p className={`mt-2 leading-7 ${theme === 'dark' ? 'text-slate-300' : 'text-stone-700'}`}>{result.summary_data.summary || 'No summary returned.'}</p>
            </div>
            <div>
              <div className={`text-xs uppercase tracking-[0.2em] ${theme === 'dark' ? 'text-amber-400' : 'text-forest font-semibold'}`}>Notion</div>
              <p className={`mt-2 leading-7 ${theme === 'dark' ? 'text-slate-300' : 'text-stone-700'}`}>{result.notion?.message || 'No Notion status returned.'}</p>
            </div>
          </div>
        </ResultCard>
      ) : null}

      {/* <ApiResponsePanel data={result} theme={theme} /> */}
    </div>
  )
}